modLoader="javafml"
loaderVersion="[49,)"
license="GNU GPL 3.0"
issueTrackerURL="https://github.com/someElseIsHere/mooojaaang/issues"

[[mods]]
modId="mooojaaang"
version="${version}"
displayName="Mooojaaang..."
displayURL="https://modrinth.com/mod/mooojaaang"
logoFile="assets/mooojaaang/icon.png"
authors="thePlaceholder"
description='''
Mooojaaang... STUDIO !!!
'''

[[dependencies.mooojaaang]]
   modId="forge"
   mandatory=true
   versionRange="[49,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.mooojaaang]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.4,)"
   ordering="NONE"
   side="BOTH"
