modLoader="javafml"
loaderVersion="[4,)"
license="GNU GPL 3.0"
issueTrackerURL="https://github.com/someElseIsHere/mooojaaang/issues"

[[mods]]
modId="mooojaaang"
version="${version}"
displayName="Mooojaaang..."
displayURL="https://modrinth.com/mod/mooojaaang"
logoFile="assets/mooojaaang/icon.png"
authors="thePlaceholder"
description='''
Mooojaaang... STUDIO !!!
'''

[[dependencies.mooojaaang]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.mooojaaang]]
modId="minecraft"
type="required"
versionRange="[1.21,)"
ordering="NONE"
side="BOTH"

[[dependencies.mooojaaang]]
modId="architectury"
type="required"
versionRange="[13.0.1,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config= "mooojaaang.mixins.json"